create sequence hibernate_sequence start with 1 increment by 1;

create table users
(
    email           varchar(255) not null,
    password        varchar(255) not null,
    firstname        varchar(128) not null,
    surname         varchar(128) not null,
    enabled         boolean      not null,
    loot_boxes_left integer      not null check ( loot_boxes_left >= 0),
    mill_currency   integer      not null check ( mill_currency >= 0),
    inventory_id    bigint,
    primary key (email)
);

create table inventory
(
    id         bigint generated by default as identity,
    user_email varchar(255)
);

create table inventory_items
(
    items_id     bigint not null,
    inventory_id bigint not null
);

create table items
(
    id          bigint generated by default as identity,
    description varchar(255) not null,
    price       integer      not null,
    rarity      varchar      not null,
    title       varchar(128) not null unique,
    quantity    integer      not null default 0,
    primary key (id)
);

create table user_roles
(
    user_email varchar(255) not null,
    roles      varchar(255)
);